---CRM RETAIL ---

--HERBİR MÜŞTERİNİN İLK ALIŞBERİŞİNDEN BU YANA GEÇEN ZAMAN  TENURE
SELECT CRM.CustomerID, 
       DATEDIFF(DAY, MIN(CRM.InvoiceDate), '20111209') AS TenureInDays
FROM PLAYGROUND.dbo.CRM AS CRM
GROUP BY CRM.CustomerID;

--HER BİR MÜŞTERİNİN ALIŞBERİŞLERİNDEN   KAZANDIIRDIĞI DEĞER MONETARY
SELECT CRM.CustomerID,
    SUM(UnitPrice*Quantity) AS MONETARY
FROM PLAYGROUND.dbo.CRM AS CRM
GROUP BY CRM.CustomerID 

-- HER BİR MÜŞTERİNİN ORTALAM SEPET DEĞERİ BASKET SIZE
SELECT CRM.CustomerID, 
       AVG(CRM.UnitPrice * CRM.Quantity) AS avg_basket_value
FROM PLAYGROUND.dbo.CRM AS CRM
GROUP BY CRM.CustomerID;

-- HER BİR MÜŞTERİNİN İLK SON SİPARİŞİNDEN BU YANA GEÇEN ZAMAN RECENCY DEĞERİ
SELECT CRM.CustomerID, 
       DATEDIFF(DAY, MAX(CRM.InvoiceDate), '20111209') AS Recency
FROM PLAYGROUND.dbo.CRM AS CRM
GROUP BY CRM.CustomerID;

-- HER BİR MÜŞTERİNİN ALIŞVERİŞ SAYISI FREKANS
SELECT CRM.CustomerID, 
       COUNT(CRM.InvoiceNo) AS Frequency
FROM PLAYGROUND.dbo.CRM AS CRM
GROUP BY CRM.CustomerID;